### ISSUE TITLE
EWAS fusion to calculate the Weight

### ISSUE THREAD

**Issue by xtmgah** [jinghuazhao/EWAS-fusion#1]
Hello 

We previously used fusion for our RNA-seq data for TWAS analysis and it work pretty well. However, we want to extend the TWAS analysis to EWAS analysis by using replacing EPIC array (450k) data. We tried to calculate the functional weight for each probe based on the normalized beta value (0-1). However, we fund it's alway skipped the calculation due to the following error. Do you have similar error when you calculated the weight? Thanks. 

"test_cg19923810 does not exist, likely GCTA could not converge, skipping gene".

Then we did some analysis and found we found there is aways a error during the gcta program:

gcta_nr_robust --grm test_cg19923810 --pheno test_cg19923810.pheno --qcovar mQTL_methylation.combined_covariates.txt --out test_cg19923810 --reml --reml-no-constrain --reml-lrt 1

Genome-wide Complex Trait Analysis (GCTA)
version 1.21
(C) 2010 Jian Yang, Hong Lee, Michael Goddard and Peter Visscher
The University of Queensland
Analysis started: Mon Jun 3 13:44:11 2019

Options:
--grm test_cg19923810
--pheno test_cg19923810.pheno
--qcovar mQTL_methylation.combined_covariates.txt
--out test_cg19923810
--reml
--reml-no-constrain
--reml-lrt 1

Note: This is a multi-thread program. You could specify the number of threads by the --thread-num option to speed up the computation if there are multiple processors in your machine.

Reading IDs of the GRM from [test_cg19923810.grm.id].
108 IDs read from [test_cg19923810.grm.id].
Reading the GRM from [test_cg19923810.grm.bin].
Reading the number of SNPs for the GRM from [test_cg19923810.grm.N.bin].
Pairwise genetic relationships between 108 individuals are included from [test_cg19923810.grm.bin].
Reading phenotypes from [test_cg19923810.pheno].
Nonmissing phenotypes of 108 individuals are included from [test_cg19923810.pheno].
Reading quantative covariates from [mQTL_methylation.combined_covariates.txt].
18 quantative covarites of 109 individuals read from [mQTL_methylation.combined_covariates.txt].

18 quantitative variable(s) included as covariate(s).
108 individuals are in common in these files.

Performing REML analysis ... (Note: may take hours depending on sample size).
108 observations, 19 fixed effect(s), and 2 variance component(s)(including residual variance).
Calculating prior values of variance components by EM-REML ...

Error: the X^t * V^-1 * X matrix is not invertible. Please check the covariate(s) and/or the environmental factor(s).

Analysis finished: Mon Jun 3 13:44:11 2019
Computational time: 0:0:0

**Comment by jinghuazhao** [comment]
The error message is a generic issue of GCTA due to an ill-conditioned GRM. Although this happened occasionally, I found it generally worked very well with EWAS.

As GRM relates to the genotype data, you make want to carefully select SNPs. The FUSION framework is happy with HapMap version.

________________________________

**Comment by xtmgah** [comment]
Thanks for your information. Did EWAS FUSION have the example to create the weights based on our owner  methylation data? Current, I used the r code in fusion similar to TWAS.  Also, do we need to transform our normalized beta value ( for example, quantile normalization)?

Best,

Tongwu

**Comment by jinghuazhao** [comment]
At least we were not aware of this -- our pipeline was built in analogy to TWAS/FUSION since the developers reframed their implementation at about the same time we worked methylation data.

I don't feel any particulars with the data transformation -- it all boils down to your own settings. In our case, I have regression residuals from colleagues.

________________________________

**Comment by xtmgah** [comment]
Hello Jinghua:

Did you use modify "gcta_nr_robust"? If yes, could you share to us and we definitely will cite your paper.  BTW, Is your EWAS pipeline manuscript submitted? Can you let me know your email address so we could reach you by email.

**Comment by jinghuazhao** [comment]
I could not recall if I ever modified it but certainly I could share this with you. I left my old workplace so I haven't written anything about this. You can reach me via jinghuazhao@hotmail.com

**Comment by xtmgah** [comment]
Thanks for your reply. We just send email to you. Can you share the "gcta_nr_robust" to us, we want to test if it will working for us. you could send me email back. Thanks.

**Comment by jinghuazhao** [comment]
The modified version of fusion_twas is with EWAS-fusion now.
